// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import StimulusReflex from "stimulus_reflex"
import consumer from "../channels/consumer"
import controller from "./application_controller"
import CableReady from "cable_ready"

import CableFromController from "./cable_from_controller"
application.register("cable-from", CableFromController)
import IdeController from "./ide_controller"
application.register("ide", IdeController)
import DEController from "./de_controller"
application.register("de", DEController)
import AppWindowController from "./app_window_controller"
application.register("app-window", AppWindowController)
import TerminalController from "./terminal_controller"
application.register("terminal", TerminalController)
import TaskbarController from "./taskbar_controller"
application.register("taskbar", TaskbarController)
import MonacoController from "./monaco_controller"
application.register("monaco", MonacoController)
import ResponsiveBoxController from "./responsive_box_controller"
application.register("responsive-box", ResponsiveBoxController)
import MonitoringController from "./monitoring_controller"
application.register("monitoring", MonitoringController)
import FileController from "./file_controller"
application.register("file", FileController)

application.consumer = consumer

StimulusReflex.initialize(application, { controller, isolate: true })
StimulusReflex.debug = true
CableReady.initialize({ consumer })
