// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import StimulusReflex from "stimulus_reflex"
import consumer from "../channels/consumer"
import controller from "./application_controller"
import CableReady from "cable_ready"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
import CableFromController from "./cable_from_controller"
application.register("cable-from", CableFromController)
import IdeController from "./ide_controller"
application.register("ide", IdeController)
import CodeEditorController from "./code_editor_controller"
application.register("code-editor", CodeEditorController)
import DesktopController from "./desktop_controller"
application.register("desktop", DesktopController)
import AppWindowController from "./app_window_controller"
application.register("app-window", AppWindowController)

application.consumer = consumer

StimulusReflex.initialize(application, { controller, isolate: true })
StimulusReflex.debug = true
CableReady.initialize({ consumer })
